sq-poller: Fix reference to undefined self.prompt in _ssh_connect
_ssh_connect was refactored in PR #877 and introduced a reference to self.prompt before prompt was defined.

This resulted in the error:
suzieq.poller.worker.nodes.node - ERROR - Unable to create persistent SSH session for 1.2.3.4 due to 'IosXENode' object has no attribute 'prompt'

Signed-off-by: Chris Bennett <chris@ceegeebee.com>