Fix test error for ospf parsing
test_ospf_parsing exited with error:
KeyError: "['instance', 'areaStub'] not in index"
which was due to not renaming the columns before dropping them.

Signed-off-by: Claudio Usai <claudio.usai@stardustsystems.net>